//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 09:42:51 PM EST 
//


package ticketpremiun.arquitectura.espe.edu.ec.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for localidad complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="localidad"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CODIGO_LOCALIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DISPONIBILIDAD" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PRECIO" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "localidad", propOrder = {
    "codigolocalidad",
    "disponibilidad",
    "precio"
})
public class Localidad {

    @XmlElement(name = "CODIGO_LOCALIDAD", required = true)
    protected String codigolocalidad;
    @XmlElement(name = "DISPONIBILIDAD", required = true)
    protected String disponibilidad;
    @XmlElement(name = "PRECIO")
    protected float precio;

    /**
     * Gets the value of the codigolocalidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGOLOCALIDAD() {
        return codigolocalidad;
    }

    /**
     * Sets the value of the codigolocalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGOLOCALIDAD(String value) {
        this.codigolocalidad = value;
    }

    /**
     * Gets the value of the disponibilidad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDISPONIBILIDAD() {
        return disponibilidad;
    }

    /**
     * Sets the value of the disponibilidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDISPONIBILIDAD(String value) {
        this.disponibilidad = value;
    }

    /**
     * Gets the value of the precio property.
     * 
     */
    public float getPRECIO() {
        return precio;
    }

    /**
     * Sets the value of the precio property.
     * 
     */
    public void setPRECIO(float value) {
        this.precio = value;
    }

}
