//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 09:42:51 PM EST 
//


package ticketpremiun.arquitectura.espe.edu.ec.ws;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ticketpremiun.arquitectura.espe.edu.ec.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ticketpremiun.arquitectura.espe.edu.ec.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObtenerPartidosDisponiblesRequest }
     * 
     */
    public ObtenerPartidosDisponiblesRequest createObtenerPartidosDisponiblesRequest() {
        return new ObtenerPartidosDisponiblesRequest();
    }

    /**
     * Create an instance of {@link ObtenerPartidosDisponiblesResponse }
     * 
     */
    public ObtenerPartidosDisponiblesResponse createObtenerPartidosDisponiblesResponse() {
        return new ObtenerPartidosDisponiblesResponse();
    }

    /**
     * Create an instance of {@link Partido }
     * 
     */
    public Partido createPartido() {
        return new Partido();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadesPrecioRequest }
     * 
     */
    public ObtenerLocalidadesPrecioRequest createObtenerLocalidadesPrecioRequest() {
        return new ObtenerLocalidadesPrecioRequest();
    }

    /**
     * Create an instance of {@link Localidad }
     * 
     */
    public Localidad createLocalidad() {
        return new Localidad();
    }

    /**
     * Create an instance of {@link ObtenerLocalidadesPrecioResponse }
     * 
     */
    public ObtenerLocalidadesPrecioResponse createObtenerLocalidadesPrecioResponse() {
        return new ObtenerLocalidadesPrecioResponse();
    }

    /**
     * Create an instance of {@link DecrementarValorDisponibilidadRequest }
     * 
     */
    public DecrementarValorDisponibilidadRequest createDecrementarValorDisponibilidadRequest() {
        return new DecrementarValorDisponibilidadRequest();
    }

    /**
     * Create an instance of {@link DecrementarValorDisponibilidadResponse }
     * 
     */
    public DecrementarValorDisponibilidadResponse createDecrementarValorDisponibilidadResponse() {
        return new DecrementarValorDisponibilidadResponse();
    }

}
