//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 09:42:51 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ec.edu.espe.arquitectura.ticketpremiun/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ticketpremiun.arquitectura.espe.edu.ec.ws;
