//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.29 at 09:42:51 PM EST 
//


package ticketpremiun.arquitectura.espe.edu.ec.ws;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import lombok.Data;



/**
 * <p>Java class for partido complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="partido"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CODIGO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CODIGO_LOCALIDAD" type="{http://ec.edu.espe.arquitectura.ticketpremiun/ws}localidad"/&gt;
 *         &lt;element name="EQUIPO_LOCAL" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="EQUIPO_VISITA" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FECHA" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="LUGAR" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "partido", propOrder = {
    "codigo",
    "codigolocalidad",
    "equipolocal",
    "equipovisita",
    "fecha",
    "lugar"
})
@Entity
@Data
@Table(name = "producto")
public class Partido implements Serializable {

    @Id
    @Column(name = "CODIGO", nullable = false, length = 20)
    @XmlElement(name = "CODIGO", required = true)
    protected String codigo;
    @Column(name = "CODIGO_LOCALIDAD", nullable = false, length = 100)
    @XmlElement(name = "CODIGO_LOCALIDAD", required = true)
    protected Localidad codigolocalidad;
    @Column(name = "EQUIPO_LOCAL", nullable = false, length = 100)
    @XmlElement(name = "EQUIPO_LOCAL", required = true)
    protected String equipolocal;
    @Column(name = "EQUIPO_VISITA", nullable = false, length = 100)
    @XmlElement(name = "EQUIPO_VISITA", required = true)
    protected String equipovisita;
     @Column(name = "FECHA", nullable = false, length = 100)
    @XmlElement(name = "FECHA", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
     @Column(name = "LUGAR", nullable = false, length = 100)
    @XmlElement(name = "LUGAR", required = true)
    protected String lugar;

    /**
     * Gets the value of the codigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODIGO() {
        return codigo;
    }

    /**
     * Sets the value of the codigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODIGO(String value) {
        this.codigo = value;
    }

    /**
     * Gets the value of the codigolocalidad property.
     * 
     * @return
     *     possible object is
     *     {@link Localidad }
     *     
     */
    public Localidad getCODIGOLOCALIDAD() {
        return codigolocalidad;
    }

    /**
     * Sets the value of the codigolocalidad property.
     * 
     * @param value
     *     allowed object is
     *     {@link Localidad }
     *     
     */
    public void setCODIGOLOCALIDAD(Localidad value) {
        this.codigolocalidad = value;
    }

    /**
     * Gets the value of the equipolocal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEQUIPOLOCAL() {
        return equipolocal;
    }

    /**
     * Sets the value of the equipolocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEQUIPOLOCAL(String value) {
        this.equipolocal = value;
    }

    /**
     * Gets the value of the equipovisita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEQUIPOVISITA() {
        return equipovisita;
    }

    /**
     * Sets the value of the equipovisita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEQUIPOVISITA(String value) {
        this.equipovisita = value;
    }

    /**
     * Gets the value of the fecha property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFECHA() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFECHA(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the lugar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLUGAR() {
        return lugar;
    }

    /**
     * Sets the value of the lugar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLUGAR(String value) {
        this.lugar = value;
    }

}
